Cloudwatch
toledompm/devops-infrastructure pull request #11
Opened 2021-05-31 22:08 UTC by leon-lopes

2021-06-01 00:10 UTC, jasondavindev commented on .terraform.lock.hcl
> +# This file is maintained automatically by "terraform init".
Adiciona esse arquivo no gitignore

2021-06-01 00:12 UTC, jasondavindev requested changes

2021-06-01 00:12 UTC, jasondavindev commented on modules/ecs/main.tf
> +      }
Vai precisar adicionar isso no task definition no repo da aplicação

2021-06-01 00:12 UTC, jasondavindev commented on modules/ecs/main.tf
> +}
Isso poderia ser criado em um módulo separado, por exemplo, `monitoring`. Se precisar de uma ajuda nisso, me pinga.

2021-06-01 00:12 UTC, jasondavindev commented on .terraform.lock.hcl
> +provider "registry.terraform.io/hashicorp/aws" {
Esse arquivo precisa estar no gitignore

2021-06-01 01:12 UTC, leon-lopes commented on modules/ecs/main.tf
> +      }
Adicionei lá

2021-06-02 21:48 UTC, jasondavindev approved these changes

2021-06-02 22:40 UTC, merged