CD/CI Terraform
toledompm/devops-infrastructure pull request #15
Opened 2021-06-03 03:18 UTC by NicolasFujisawa

2021-06-03 03:24 UTC, NicolasFujisawa commented
@toledompm Depois chama eu ou o jason pra configurar o deploy manual.

obs: precisa add tbm uma secret no repo: REGION=us-east-1 :)

2021-06-03 13:15 UTC, jasondavindev commented on .github/workflows/staging.yml
> +      - '**'
Faltou ignorar a main

2021-06-03 13:16 UTC, jasondavindev requested changes

2021-06-03 13:16 UTC, jasondavindev commented on .github/workflows/staging.yml
> +      - '**'
Faltou ignorar a main

2021-06-03 13:16 UTC, jasondavindev commented on modules/rds/variables.tf
> +  default     = "taskapp-db"
Não pode ter ifem

2021-06-03 13:18 UTC, jasondavindev commented on modules/rds/main.tf
> +  identifier             = var.identifier
Na real não precisa alterar, tu já setou o valor default na variavel `DB_NAME` no variables.tf da raiz

2021-06-03 13:18 UTC, jasondavindev commented on modules/rds/variables.tf
> +  default     = "taskapp-db"
Como dito no comentário anterior, não precisa mais porque já setou o valor default da `DB_NAME` na raiz, aí só passar ela pra cá.

2021-06-04 16:41 UTC, NicolasFujisawa commented on .github/workflows/staging.yml
> +      - '**'
Coloquei como on: pull_request, assim só roda a action em pull_request abertas, se ignorar a main nenhum trigger é ativado

2021-06-04 16:43 UTC, NicolasFujisawa commented on modules/rds/main.tf
> +  identifier             = var.identifier
Separei o var.name pra não setar uma env pra duas env's, assim ele pega o valor default mesmo.

2021-06-04 16:45 UTC, NicolasFujisawa commented on modules/rds/variables.tf
> +  default     = "taskapp-db"
- Esse aqui até que aceita o hyphen, o que não pode é o db_name, esse seria o identifier.


- No comentário abaixo expliquei porque criei um valor default para a variavel identifier, não está usando o DB_NAME nessa variavel.

2021-06-04 17:27 UTC, jasondavindev commented on .github/workflows/staging.yml
> +      - '**'
Deixa no push porque toda vez que fizer um commit, eu quero ver o plan. Do jeito que está hoje eu só consigo ver o plan quando abrir um PR. Isso não faz sentido.

2021-06-04 17:27 UTC, jasondavindev commented on modules/rds/variables.tf
> +  default     = "taskapp-db"
Por convenção, deixa sem hífen

2021-06-05 17:55 UTC, toledompm approved these changes

2021-06-05 17:56 UTC, merged